### ISSUE TITLE
 How can I download  srlconll scripts， it often can't connect to the website and fails

### ISSUE THREAD

**Issue by yueguangxichen** [XMUNLP/Tagger#11]
http://www.lsi.upc.edu/%7Esrlconll/soft.html 
I couldn't download it, would you mind if you send the file to me?

**Comment by Playinf** [comment]
I've uploaded the [srlconll-1.1.zip](https://github.com/XMUNLP/Tagger/files/2321409/srlconll-1.1.zip).
