### ISSUE TITLE
请问训练脚本中的train_path是指序列化以后的文件么？

### ISSUE THREAD

**Issue by imucsliurui** [XMUNLP/Tagger#3]
直接给定路径好像不可以。
报错信息是 ： No data files found in XXXX

请问这个如何解决？

![555555555555555555555555555522750](https://user-images.githubusercontent.com/25268285/38169863-264b18fe-35a8-11e8-88fb-1b17bf05e354.png)

**Comment by Playinf** [comment]
原始文件需要使用input_convert.py转换成tf.Record格式，会生成类似`conll05-train-00000-of-00010`的文件，并且命名中必须包含`train`。
