### ISSUE TITLE
Preparing the validation script

### ISSUE THREAD

**Issue by imucsliurui** [XMUNLP/Tagger#4]
SRLPATH=/PATH/TO/SRLCONLL
TAGGERPATH=/PATH/TO/TAGGER
DATAPATH=/PATH/TO/DATA

export PERL5LIB="$SRLPATH/lib:$PERL5LIB"
export PATH="$SRLPATH/bin:$PATH"

python $TAGGERPATH/main.py predict --data_path # **$DATAPATH/conll05.devel.txt** \
  --model_dir train  --model_name deepatt \
  --vocab_path $DATAPATH/word_dict $DATAPATH/label_dict \
  --device_list 0 \
  --decoding_params="decode_batch_size=512" \
  --model_params="num_hidden_layers=10,feature_size=100,hidden_size=200,filter_size=800"
python $TAGGERPATH/scripts/convert_to_conll.py#  **conll05.devel.txt.deepatt.decodes** **# $DATAPATH/conll05.devel.props.gold.txt** output
perl $SRLPATH/bin/srl-eval.pl  # **$DATAPATH/conll05.devel.props. output**

请问以上加粗的文件名 对应的文件分别是什么格式？好像项目中并没有给出，可否分享下，谢谢！

**Comment by Playinf** [comment]
conll05.devel.txt.deepatt.decodes是predict脚本的输出文件。output是convert_to_conll.py的输出文件。其他文件只要按照deep_srl中提供的说明都能够生成。

**Comment by imucsliurui** [comment]
嗯，感谢回答。
另外，我在训练阶段，准备好dev文件后，生成的eval_input_fn，在evaluation阶段得到的f_measure和precision 和recall都为0，
但是，将train_input_fn赋值给eval_input_fn得到的三个指标又都是1.
请问这是什么原因？
谢谢
