### ISSUE TITLE
训练脚本疑问

### ISSUE THREAD

**Issue by hrdxwandg** [XMUNLP/Tagger#6]
python tagger/main.py train \
    --data_path TRAIN_PATH --model_dir train --model_name deepatt \
    --vocab_path word_dict label_dict --emb_path glove.6B.100d.txt \
    --model_params=feature_size=100,hidden_size=200,filter_size=800,residual_dropout=0.2, \
                   num_hidden_layers=10,attention_dropout=0.1,relu_dropout=0.1 \
    -training_params=batch_size=4096,eval_batch_size=1024,optimizer=Adadelta,initializer=orthogonal, \
                      use_global_initializer=false,initializer_gain=1.0,train_steps=600000, \
                      learning_rate_decay=piecewise_constant,learning_rate_values=[1.0,0.5,0.25], \
                      learning_rate_boundaries=[400000,500000],device_list=[0],clip_grad_norm=1.0 \ 
    **--validation_params=script=run.sh**

问下最后一个参数run.sh这个脚本是哪个？仓库貌似没有。先谢过了。

**Comment by Playinf** [comment]
run.sh的内容在Preparing the validation script一节中描述。

**Comment by hrdxwandg** [comment]
好的。谢谢
