### ISSUE TITLE
一个bug问题

### ISSUE THREAD

**Issue by hrdxwandg** [XMUNLP/Tagger#7]
首先感谢作者分享的代码。

在测试时发现一个问题：
1 `` Wait ! ! Wait '' ! ! Cried the guard who ran from the hut to shout to other men standing about outside . ||| O B-V O O O O O O O O O O O O O O O O O O O O O O O
4 `` Wait ! ! Wait '' ! ! Cried the guard who ran from the hut to shout to other men standing about outside . ||| O O O O B-V O O O O O O O O O O O O O O O O O O O O

比如在对这两个case做预测时，发现遇到“!”后，预测就停止了。导致长度被截断。用perl脚本做验证时报错。把"!"换成"."就没问题了。

**Comment by Playinf** [comment]
我单独测试没有问题，不知道你是不是没有换行。
