### ISSUE TITLE
How do you get the data with the propId?

### ISSUE THREAD

**Issue by huihuifan** [XMUNLP/Tagger#8]
If you run the pretrained model with this data file: https://github.com/luheng/deep_srl/blob/master/sample_data/sentences_with_predicates.txt

the model works. I'm wondering how I can use your repo to generate the propid before doing SRL. Do you provide this functionality?

Thank you!

**Comment by Playinf** [comment]
Do you mean how to discover the predicates of a given sentence? We are sorry that we do not have this functionality.

**Comment by huihuifan** [comment]
I used deep_srl to get the predicates
